
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authnusers-q-{{COLOR}}
  namespace: dev
  labels:
    app: authnusers-q
    color: {{COLOR}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authnusers-q
      color: {{COLOR}}
  template:
    metadata:
      labels:
        app: authnusers-q
        color: {{COLOR}}
        version: {{COLOR}}
    spec:
      containers:
      - name: authnusers-q
        image: {{IMAGE}}
        ports:
        - containerPort: 8090
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
