version: "3.8"
services:
  readercommand:
    image: readercommand:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    environment:
      SPRING_PROFILES_ACTIVE: bootstrap, jpa
    networks:
      - lms_network
    volumes:
      - "uploaded_files_volume:/tmp"
    deploy:
      replicas: 2

  postgres_in_lms_network:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    deploy:
      replicas: 2
    ports:
      - "5468-5471:5432"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"
    networks:
      - lms_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  lms_network:
    external: true

volumes:
  uploaded_files_volume:
  postgres_volume: