apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-c-{{COLOR}}
  namespace: dev
  labels:
    app: authors-c
    color: {{COLOR}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authors-c
      color: {{COLOR}}
  template:
    metadata:
      labels:
        app: authors-c
        color: {{COLOR}}
        version: {{COLOR}}
    spec:
      containers:
      - name: authors-c
        image: {{IMAGE}}
        ports:
        - containerPort: 8085
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
