
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-q-{{COLOR}}
  namespace: dev
  labels:
    app: reader-q
    color: {{COLOR}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reader-q
      color: {{COLOR}}
  template:
    metadata:
      labels:
        app: reader-q
        color: {{COLOR}}
        version: {{COLOR}}
    spec:
      containers:
      - name: reader-q
        image: {{IMAGE}}
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
