
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lendings-q
  namespace: dev
spec:
  rules:
    - host: lendings.dev.company.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lendings-q-service-stable
                port:
                  number: 8882   # se o Service exp√µe 8882
