services:
    users:
        image: lmsusers:latest
        volumes:
            - ./src:/app/src
            - ./pom.xml:/app/pom.xml
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8067:8080"
        environment:
            SPRING_PROFILES_ACTIVE: jpa, boostrap
        networks:
            - lms_network

    postgres_in_lms_network_user:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5487-5490:5432"
        networks:
            - lms_network
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 10s
            retries: 5
            timeout: 5s

#    rabbitmq_in_lms_network_user:
#        image: rabbitmq:latest
#        restart: unless-stopped
#        ports:
#            - "5678:5672" # RabbitMQ main port
#            - "15678:15672" # RabbitMQ management UI
#        environment:
#            RABBITMQ_DEFAULT_USER: guest
#            RABBITMQ_DEFAULT_PASS: guest
#        networks:
#            - lms_network2
#        healthcheck:
#            test: [ "CMD", "rabbitmqctl", "status" ]
#            interval: 10s
#            retries: 5
#            timeout: 5s

networks:
    lms_network:
        external: true