apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-readers-command-{{COLOR}}
  namespace: dev
  labels:
    app: lms-readers-command
    color: {{COLOR}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-readers-command
      color: {{COLOR}}
  template:
    metadata:
      labels:
        app: lms-readers-command
        color: {{COLOR}}
        version: {{COLOR}}
    spec:
      containers:
      - name: lms-readers-command
        image: {{IMAGE}}
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
